apiVersion: v2
name: crossplane-s3-buckets
description: Helm chart for managing S3 buckets via Crossplane
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - crossplane
  - s3
  - aws
  - buckets
maintainers:
  - name: Maxim Garmonov
    email: devops@example.com