{{- $env := .Values.environment }}
{{- $region := .Values.region }}
{{- $providerConfig := .Values.providerConfigRef }}
{{- $defaults := .Values.defaults }}
{{- $defaultTags := .Values.defaultTags }}

{{- range .Values.queues }}
{{- $queueName := printf "%s-%s" .name $env }}
{{- $team := .team | default "platform" }}
{{- $dlqEnabled := false }}
{{- if .dlq }}
  {{- if hasKey .dlq "enabled" }}
    {{- $dlqEnabled = .dlq.enabled }}
  {{- end }}
{{- end }}

{{- if $dlqEnabled }}
---
# Dead Letter Queue (DLQ)
apiVersion: sqs.aws.m.upbound.io/v1beta1
kind: Queue
metadata:
  name: {{ $queueName }}-dlq
  namespace: default
  labels:
    app: crossplane-sqs
    team: {{ $team }}
    environment: {{ $env }}
    queue-type: dlq
    queue-name: {{ $queueName }}
  annotations:
    description: "DLQ for {{ $queueName }}"
spec:
  forProvider:
    region: {{ $region }}
    visibilityTimeoutSeconds: {{ .visibilityTimeoutSeconds | default $defaults.visibilityTimeoutSeconds }}
    messageRetentionSeconds: {{ int (.dlq.messageRetentionSeconds | default $defaults.dlq.messageRetentionSeconds) }}
    maxMessageSize: {{ .maxMessageSize | default $defaults.maxMessageSize }}
    delaySeconds: {{ .delaySeconds | default $defaults.delaySeconds }}
    receiveWaitTimeSeconds: {{ .receiveWaitTimeSeconds | default $defaults.receiveWaitTimeSeconds }}
    tags:
      Name: {{ $queueName }}-dlq
      Team: {{ $team }}
      Environment: {{ $env }}
      QueueType: dlq
      {{- range $key, $value := $defaultTags }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .tags }}
      {{- range $key, $value := .tags }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
  providerConfigRef:
    name: {{ $providerConfig }}
    kind: ClusterProviderConfig
{{- end }}

---
# Main SQS Queue
apiVersion: sqs.aws.m.upbound.io/v1beta1
kind: Queue
metadata:
  name: {{ $queueName }}
  namespace: default
  labels:
    app: crossplane-sqs
    team: {{ $team }}
    environment: {{ $env }}
    queue-type: main
    queue-name: {{ $queueName }}
  annotations:
    description: "{{ .name }} queue for {{ $env }} environment"
spec:
  forProvider:
    region: {{ $region }}
    visibilityTimeoutSeconds: {{ .visibilityTimeoutSeconds | default $defaults.visibilityTimeoutSeconds }}
    messageRetentionSeconds: {{ int (.messageRetentionSeconds | default $defaults.messageRetentionSeconds) }}
    maxMessageSize: {{ .maxMessageSize | default $defaults.maxMessageSize }}
    delaySeconds: {{ .delaySeconds | default $defaults.delaySeconds }}
    receiveWaitTimeSeconds: {{ .receiveWaitTimeSeconds | default $defaults.receiveWaitTimeSeconds }}
    {{- if $dlqEnabled }}
    redrivePolicy: |
      {
        "deadLetterTargetArn": "${arn}",
        "maxReceiveCount": {{ .dlq.maxReceiveCount | default $defaults.dlq.maxReceiveCount }}
      }
    redriveAllowPolicy: |
      {
        "redrivePermission": "byQueue",
        "sourceQueueArns": []
      }
    {{- end }}
    tags:
      Name: {{ $queueName }}
      Team: {{ $team }}
      Environment: {{ $env }}
      QueueType: main
      {{- range $key, $value := $defaultTags }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .tags }}
      {{- range $key, $value := .tags }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
  providerConfigRef:
    name: {{ $providerConfig }}
    kind: ClusterProviderConfig
{{- end }}
